---
# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- name: run python with hobart_search
  shell: nohup python3 tweepy_search_hobart.py > hobart 2>&1 &
  args:
    chdir: /home/ubuntu/crawler/tweepy

- name: run python with melbourne_search
  shell: nohup python3 tweepy_search_melbourne.py > melbourne 2>&1 &
  args:
    chdir: /home/ubuntu/crawler/tweepy


# - name: run python with hobart_stream
#   shell: nohup python3 tweepy_stream_hobart_4thmay.py > /dev/null 2>&1 &
#   args:
#     chdir: /home/ubuntu/crawler/tweepy_stream

# - name: run python with melbourne_stream
#   shell: nohup python3 tweepy_stream_melbourne_4thmay.py > /dev/null 2>&1 &
#   args:
#     chdir: /home/ubuntu/crawler/tweepy_stream


# - name: run python with hobart_scenario
#   shell: nohup python3 scenario_hobart_may_3rd.py > hobart 2>&1 &
#   args:
#     chdir: /home/ubuntu/crawler/tweepy_scenario

# - name: run python with melbourne_scenario
#   shell: nohup python3 scenario_melbourne_may_3rd.py > melbourne 2>&1 &
#   args:
#     chdir: /home/ubuntu/crawler/tweepy_scenario