---
# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- name: Install package by apt(sudo apt install)
  tags: always
  become: yes
  apt:
    name: ['python-pip', 'git', 'python3-pip', 'python3-setuptools', 'unzip', 'net-tools']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest