---
# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- name: Add nodes
  become: yes
  docker_swarm:
    state: join
    advertise_addr: eth0:2377
    join_token: '{{ swarm_token }}'
    remote_addrs: ['{{ web_ip }}:2377']
