- name: Check folder
  stat:
    path: /home/ubuntu/app
  register: flask_app_dir

- name: create app folder
  file:
    path: /home/ubuntu/app
    state: directory
    mode: 0777
  when: flask_app_dir.stat.exists == false

- name: Copy flask app from local to remote
  copy:
    src: /Users/xuzheng/Projects/COMP90024-Project/backend/flaskhttp/
    dest: /home/ubuntu/app

# - name: stop docker-compose
#   become: yes
#   command: docker-compose down -f /home/ubuntu/app/docker-compose.yml --rmi all

- name: stop docker-compose
  become: yes
  raw: cd /home/ubuntu/app; docker-compose down --rmi all

- name: start docker-compose
  become: yes
  raw: cd /home/ubuntu/app; docker-compose up --build --force-recreate -d
