---
- name: Format disk
  filesystem: 
    fstype: ext4
    dev: /dev/vdb
    force: true
- name: Mount volume
  mount:
    path: /data
    src: /dev/vdb
    fstype: ext4
    state: mounted


- name: mkdir the mount point
  become: yes
  shell: |
    mkfs.ext4 /dev/vdb
    sudo mount /dev/vdb /opt
    sleep 3


- name: attach master volume to master
  os_server_volume:
    state: present
    server: '{{ os_instance_ids|first }}'
    volume: '{{ os_vol_ids|first }}'
    device: /dev/vdb
- name: attach volume1 to instance1
  os_server_volume:
    state: present
    server: '{{ os_instance_ids|second }}'
    volume: '{{ os_vol_ids|second }}'
    device: /dev/vdb
- name: attach volume2 to instance2
  os_server_volume:
    state: present
    server: '{{ os_instance_ids|third }}'
    volume: '{{ os_vol_ids|third }}'
    device: /dev/vdb

