---
# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- name: Create /data
  become: yes
  file: 
    path: /data
    state: directory
    mode: 0777

- name: chmod 777 -R /data
  become: yes
  command: chmod 777 -R /data

- name: Format disk
  become: yes
  filesystem: 
    fstype: ext4
    dev: /dev/vdb
    force: true

- name: Mount volume
  become: yes
  mount:
    path: /data
    src: /dev/vdb
    fstype: ext4
    state: mounted

- name: chmod 777 -R /data
  become: yes
  command: chmod 777 -R /data

# - name: mkdir the mount point
#   become: yes
#   shell: |
#     sudo mkfs -t ext4 /dev/vdb
#     sudo mount /dev/vdb /data
#     sleep 3