---
# - name: run python with canberra
#   shell: nohup python3 tweepy_search_canberra_may_3rd.py > /dev/null 2>&1 &
#   args:
#     chdir: /home/ubuntu/crawler/

- name: run python with darwin
  shell: nohup python3 tweepy_search_darwin_may_3rd.py > /dev/null 2>&1 &
  args:
    chdir: /home/ubuntu/crawler/