version: '3'
services:
  web_flask:
    image: zhengxu4665/my_flask
    ports:
      - '5000:5000'
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==worker]
