# - hosts: all
#   gather_facts: false

#   roles:
#     - role: proxy
#     - role: common
#     - role: docker
#     - role: mount-volume
#     - role: crawler-setup

- hosts: sub1
  gather_facts: false

  roles:
    - role: couchdb-sub1

- hosts: sub2
  gather_facts: false

  roles:
    - role: couchdb-sub2

- hosts: root
  gather_facts: false

  roles:
    - role: couchdb-root
    - role: couchdb-cluster


#---------------------------------crawler----------------------------------
# - hosts: root
#   gather_facts: false

#   roles:
#     - role: crawler-root

# - hosts: sub1
#   gather_facts: false

#   roles:
#     - role: crawler-sub1

# - hosts: sub2
#   gather_facts: false

#   roles:
#     - role: crawler-sub2

# - hosts: web
#   gather_facts: false

#   roles:
#     - role: crawler-web


