# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- hosts: all
  vars_files:
    - host_vars/vars.yaml
  gather_facts: false

  roles:
    - role: proxy
    - role: common
    - role: docker
    - role: mount-volume

#---------------------------------couchdb----------------------------------

- hosts: sub1
  gather_facts: false

  roles:
    - role: couchdb-sub1

- hosts: sub2
  gather_facts: false

  roles:
    - role: couchdb-sub2

- hosts: root
  gather_facts: false

  roles:
    - role: couchdb-root
    - role: couchdb-cluster

#---------------------------------crawler----------------------------------

- hosts: root
  gather_facts: false

  roles:
    - role: crawler-setup
    - role: crawler-root

- hosts: sub1
  gather_facts: false

  roles:
    - role: crawler-setup
    - role: crawler-sub1

- hosts: sub2
  gather_facts: false

  roles:
    - role: crawler-setup
    - role: crawler-sub2

- hosts: web
  gather_facts: false

  roles:
    - role: crawler-setup
    - role: crawler-web

#---------------------------------web----------------------------------
- hosts: web
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true
  roles:
    - role: init-swarm
    - role: deploy-nginx


- hosts: flask
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true
  roles:
    - role: join-swarm

- hosts: web
  gather_facts: true
  roles:
    - role: deploy-flask
