- hosts: localhost
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: volume
    - role: security-group
    - role: volume-snapshop
    - role: image
    - role: instance