# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- hosts: localhost
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: volume
    - role: security-group
    - role: instance
    - role: modify-vars