version: '3'
services:
  couch_sub2:
    build: .
    restart: always
    network_mode: host
    ports:
      - '5984:5984'
      - '5986:5986'
      - '4369:4369'
      - '9100-9200:9100-9200'
    volumes:
      - /data:/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=happy
      - NODENAME=172.26.132.2
      - COUCHDB_COOKIE=monster
    container_name: couch_sub2