---
# COMP90024 Cluster and Cloud Computing 2020 Semester1
# This project is developed by Group38
#
# Zhe Wang      951996
# Zheng Xu      785974
# Zeng Tian     1072955
# Miaoqin Li    998914
# Yuming Lin    883717

- name: Create /crawler
  become: yes
  file: 
    path: /home/ubuntu/crawler
    state: directory
    mode: 0777

- name: Copy root from local to remote
  copy:
    src: /Users/linyuming/Unimelb/COMP 90024 Cluster and Cloud Computing/assignment2/ansible/tweepy
    dest: /home/ubuntu/crawler

- name: Copy root from local to remote
  copy:
    src: /Users/linyuming/Unimelb/COMP 90024 Cluster and Cloud Computing/assignment2/ansible/requirements.txt
    dest: /home/ubuntu/crawler

- name: chmod 777
  become: yes
  command: chmod -R 777 /home/ubuntu/crawler

- name: install requirements
  pip:
    requirements: /home/ubuntu/crawler/requirements.txt